# Development Dockerfile
FROM ruby:3.2-alpine

# Install system dependencies
RUN apk add --no-cache \
    build-base \
    postgresql-dev \
    git \
    tzdata \
    nodejs \
    npm \
    bash \
    curl \
    vim

# Set working directory
WORKDIR /app

# Copy Gemfile and Gemfile.lock
COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle install

# Expose port
EXPOSE 3000

# Start the Rails server in development mode
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]