source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 8.0.0'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use Puma as the app server
gem 'puma', '~> 6.0'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Authentication
gem 'devise'
gem 'devise-jwt'

# API & CORS
gem 'jbuilder'
gem 'rack-cors'

# Background Jobs
gem 'redis', '~> 5.0'
gem 'sidekiq'

# Security
gem 'rack-attack'
gem 'secure_headers'

# JSON Web Tokens
gem 'jwt'

# Environment variables
gem 'dotenv-rails'

# Pagination
gem 'kaminari'

# Validation and error handling
gem 'active_model_serializers'

# Report exports
gem 'prawn'
gem 'prawn-table'
gem 'caxlsx'
gem 'caxlsx_rails'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  # Testing framework
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rspec-rails'

  # API Documentation
  gem 'rswag'
  gem 'rswag-api'
  gem 'rswag-ui'

  # Code analysis
  gem 'rubocop-rails'
  gem 'rubocop-rspec'

  # Debug
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # Documentation
  gem 'yard'
end

group :test do
  # Test coverage
  gem 'simplecov', require: false

  # Test helpers
  gem 'database_cleaner-active_record'
  gem 'shoulda-matchers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
